# Generated by Django 4.2.11 on 2024-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_remove_team_user_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
