# Generated by Django 4.2.11 on 2024-04-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
    ]
