# Generated by Django 4.2.11 on 2024-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('In PROGRESS', 'In Progress')], default='OPEN', max_length=25),
        ),
    ]
