# Generated by Django 4.2.11 on 2024-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_board_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
