# Generated by Django 4.2.11 on 2024-04-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_remove_team_status'),
        ('boardapp', '0003_board_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=25)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.team')),
            ],
        ),
    ]
